# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases
#
# For the OpenTelemetry Collector Contrib official distribution sources, check
# https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib

dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  version: 0.125.1-dev
  output_path: ./cmd/otelcontribcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension v0.125.0
  - gomod: github.com/honeycombio/opentelemetry-collector-configs/honeycombextension v0.0.0-20250421182326-acd791633ce9

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.125.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.125.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.125.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.125.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.125.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/logdedupprocessor v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.125.0
  - gomod: github.com/honeycombio/opentelemetry-collector-configs/usageprocessor v0.0.0-20250421182326-acd791633ce9

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.125.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/libhoneyreceiver v0.125.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.125.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.31.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.31.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/aesprovider v0.125.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/secretsmanagerprovider v0.125.0

# When using `make genotelcontribcol`, a `replaces` section is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# Contrib modules.
replaces:
  - github.com/honeycombio/opentelemetry-collector-configs/usageprocessor => github.com/honeycombio/opentelemetry-collector-configs/usageprocessor v0.0.0-20250421182326-acd791633ce9
